from fpdf import FPDF
import tempfile
import os

class PDF(FPDF):
    def __init__(self):
        super().__init__()
        # Check for the font file (ipaexg.ttf) as you mentioned it is already there.
        # This helps render special characters (like Japanese yen symbol or mixed text) if needed,
        # even if the main report is in English.
        self.font_path = 'ipaexg.ttf' 
        self.use_custom_font = os.path.exists(self.font_path)
        
        if self.use_custom_font:
            self.add_font('CustomFont', '', self.font_path, uni=True)
            self.set_font('CustomFont', '', 10)
        else:
            # Fallback to standard Arial if the file is missing, standard for English
            self.set_font('Arial', '', 10)

    def header(self):
        if self.use_custom_font:
            self.set_font('CustomFont', '', 14)
        else:
            self.set_font('Arial', 'B', 14)
            
        self.cell(0, 10, 'Portfolio Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        if self.use_custom_font:
            self.set_font('CustomFont', '', 8)
        else:
            self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        if self.use_custom_font:
            self.set_font('CustomFont', '', 12)
        else:
            self.set_font('Arial', 'B', 12)
            
        self.set_fill_color(230, 230, 230) # Light gray background
        self.cell(0, 8, str(title), 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        if self.use_custom_font:
            self.set_font('CustomFont', '', 10)
        else:
            self.set_font('Arial', '', 10)
            
        # multi_cell handles wrapping automatically
        self.multi_cell(0, 5, str(body))
        self.ln()

    def check_space(self, height_needed):
        """
        Checks if there is enough space on the current page.
        If not, it adds a new page.
        height_needed: Height in mm.
        """
        # A4 height is ~297mm. We leave ~15mm for bottom margin.
        page_break_trigger = 275 
        if self.get_y() + height_needed > page_break_trigger:
            self.add_page()

def create_pdf_report(payload, figs):
    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    if not payload:
        pdf.chapter_title("No Data Available")
        return bytes(pdf.output())

    # --- 1. Advisor's Note ---
    # This prints the text from the sidebar text area
    if 'advisor_note' in payload and payload['advisor_note']:
        pdf.chapter_title("1. Advisor's Note")
        pdf.chapter_body(payload['advisor_note'])
        pdf.ln(5)

    # --- 2. Executive Summary (AI Diagnosis) ---
    if 'ai_diagnosis' in payload:
        diag = payload['ai_diagnosis']
        pdf.check_space(50) # Ensure title and summary stick together
        pdf.chapter_title("2. Executive Summary (AI Diagnosis)")
        
        summary_text = (
            f"Type: {diag.get('status', '-')}\n"
            f"Risk Assessment: {diag.get('risk', '-')}\n"
            f"Action Plan: {diag.get('action', '-')}\n"
        )
        pdf.chapter_body(summary_text)

        # Print the detailed review string generated by the app
        if 'detailed_review' in payload:
             pdf.ln(2)
             pdf.set_font('CustomFont' if pdf.use_custom_font else 'Arial', 'U', 10) # Underline title
             pdf.cell(0, 6, "Detailed Analysis:", 0, 1)
             
             pdf.set_font('CustomFont' if pdf.use_custom_font else 'Arial', '', 9)
             pdf.multi_cell(0, 5, str(payload['detailed_review']))
             pdf.ln()

    # --- 3. Key Metrics ---
    if 'metrics' in payload:
        pdf.check_space(40)
        pdf.chapter_title("3. Key Risk & Return Metrics")
        
        metrics_str = ""
        for k, v in payload['metrics'].items():
            metrics_str += f" - {k}: {v}\n"
        
        if 'mc_stats' in payload:
            metrics_str += f"\n[Monte Carlo Simulation]\n{payload['mc_stats']}"
            
        pdf.chapter_body(metrics_str)

    # --- 4. Factor Analysis ---
    if 'factor_comment' in payload:
        pdf.check_space(30)
        pdf.chapter_title("4. Factor Analysis")
        pdf.chapter_body(payload['factor_comment'])

    # --- 5. Visual Analysis (Graphs) ---
    if figs:
        pdf.add_page()
        pdf.chapter_title("5. Visual Analysis")
        
        # Define the order of charts
        order = ['pie', 'history', 'mc', 'correlation', 'factor_beta', 'attribution']
        
        for key in order:
            if key in figs:
                fig = figs[key]
                # Format title: "factor_beta" -> "FACTOR BETA"
                title = key.replace('_', ' ').upper()
                
                try:
                    # Logic: Check if there is space for Title (8mm) + Image (approx 85mm)
                    # If not, add a new page before printing the title.
                    pdf.check_space(95) 
                    
                    pdf.set_font('CustomFont' if pdf.use_custom_font else 'Arial', 'B', 10)
                    pdf.cell(0, 8, f"[Chart: {title}]", 0, 1)

                    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmpfile:
                        # Use scale=2 for higher resolution images in the PDF
                        fig.write_image(tmpfile.name, format="png", engine="kaleido", scale=2)
                        img_path = tmpfile.name
                    
                    # Insert image. w=170 fills most of the A4 width
                    pdf.image(img_path, w=170)
                    
                    # Clean up
                    os.unlink(img_path) 
                    pdf.ln(5)
                    
                except Exception as e:
                    pdf.cell(0, 10, f"[Error rendering chart {title}: {str(e)}]", 0, 1)

    # CRITICAL: Convert to bytes before returning to avoid Streamlit crash
    return bytes(pdf.output())
